Repository mamoe/mirai, pull requests merged in 2020-08, with the labels that each got.

#495 Fix Method.registerEvent for Kotlin functions
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/GroupImpl.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/util.kt
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/event/internal/EventInternalJvm.kt
Labels: M, 　bug　

#499 Fix the abnormal behavior of ListenerHost.
  java-test/src/test/java/net/mamoe/mirai/javatest/SimpleListenerHostTest.java
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/event/internal/EventInternalJvm.kt
Labels: M, 　bug　

#498 日志系统可以重定向为log4j等jvm日志系统
  buildSrc/src/main/kotlin/Versions.kt
  mirai-core/build.gradle.kts
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/utils/LoggerAdapters.kt
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/utils/internal/logging/JdkLogger.kt
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/utils/internal/logging/Log4jLogger.kt
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/utils/internal/logging/Slf4jLogger.kt
Labels: N, feature

#502 Add send silk format voice support, fix typo.
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/GroupImpl.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Group.kt
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/message/SendImageUtilsJvm.kt
Labels: N, protocol

#504 支持解析好友输入状态
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/data/proto/msgType0x210.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/friend.kt
Labels: feature, protocol

#507 Support Nick changed event
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.common.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/FriendImpl.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/MemberImpl.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/QQAndroidBotNetworkHandler.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/bot.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/friend.kt
Labels: N, feature

#487 update some unknown fields
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/Tlv.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/login/WtLogin.kt
Labels: enhancement, protocol
