Repository mamoe/mirai, pull requests merged in 2020-09, with the labels that each got.

#561 Fix #550: NoSuchElementException when concatenating an EmptyMessageChain with another
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/message/data/impl.kt
Labels: M, 　bug　

#505 change the way of device lock verify
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/utils/HyperLinkLabel.kt
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/utils/LoginSolver.swing.jvm.kt
Labels: N, enhancement

#525 Update Tlv.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/Tlv.kt
Labels: N, enhancement, ready-to-merge

#501 Add low level api for getting group honor members list.
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.common.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/data/GroupHonorListData.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/lowLevelApi.kt
Labels: N, feature, protocol, ready-to-merge

#584 Fix: add host for Voice.url
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/message/data/Voice.kt
Labels: N, protocol, ready-to-merge, 　bug　

#596 Fix Ansi Pollution
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/utils/PlatformLogger.jvm.kt
Labels: N, ready-to-merge, 　bug　

#531 Support Group Retrieve, fix #528
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/MessageSvc.PbGetMsg.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.PbPushTransMsg.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/group.kt
Labels: N, feature, protocol, ready-to-merge

#600 Support Nudge message
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/FriendImpl.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/MemberImpl.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/data/proto/OIDB.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/PacketFactory.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/NudgePacket.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Friend.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Member.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/friend.kt
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/group.kt
Labels: M, feature, feature:new-message, protocol

#509 Try to fix #358 according to @Mrs4s comment
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.PbPushTransMsg.kt
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
Labels: M, protocol, 　bug　

#615 Add missing template id in nudge decoding
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
Labels: protocol, ready-to-merge, 　bug　

#606 Fix BotJoinGroupEvent.Retrieve.toString()
  mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/group.kt
Labels: N, ready-to-merge, 　bug　

#607 Ignore auto reply message
  mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/MessageSvc.PbGetMsg.kt
Labels: M, enhancement, protocol, ready-to-merge

#543 Standard Captcha update
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/utils/LoginSolver.jvm.kt
  mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/utils/WindowHelperJvm.kt
  mirai-core/src/jvmMain/resources/net/mamoe/mirai/utils/project-mirai.png
Labels: M, enhancement
