Repository mamoe/mirai, pull requests merged in 2021-11, with the labels that each got.

#1657 Reject sending `FileMessage`
  mirai-core-api/src/commonMain/kotlin/contact/file/AbsoluteFile.kt
  mirai-core-api/src/commonMain/kotlin/message/data/FileMessage.kt
  mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
  mirai-core/src/commonMain/kotlin/contact/SendMessageHandler.kt
  mirai-core/src/commonMain/kotlin/contact/file/AbsoluteFolderImpl.kt
  mirai-core/src/commonMain/kotlin/contact/util.kt
  mirai-core/src/commonMain/kotlin/message/ForceAsLongMessage.kt
  mirai-core/src/commonMain/kotlin/utils/RemoteFileImpl.kt
Labels: enhancement, M, ready-to-merge

#1659 Handle service unavailable case when sending message, thanks to EDG
  mirai-core/src/commonMain/kotlin/contact/SendMessageHandler.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/MessageSvc.PbSendMsg.kt
Labels: enhancement, N, ready-to-merge

#1637 AbstractExternalResource
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalImageImpls.kt
  mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalResourceLeakObserver.kt
  mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
Labels: feature, N, ready-to-merge

#1671 Support `Image.isUploaded`,
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
  mirai-core-api/src/commonMain/kotlin/message/data/impl.kt
  mirai-core-api/src/commonTest/kotlin/message.data/ImageTest.kt
  mirai-core/src/commonMain/kotlin/message/InternalImageProtocolImpl.kt
  mirai-core/src/commonMain/resources/META-INF/services/net.mamoe.mirai.message.data.InternalImageProtocol
  mirai-core/src/commonTest/kotlin/message/InternalImageProtocolImplTest.kt
Labels: feature, N, ready-to-merge

#1678 Fix #1674, apply right nick and remark impl to contact design
  mirai-core/src/commonMain/kotlin/contact/AbstractMember.kt
  mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt
  mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
  mirai-core/src/commonMain/kotlin/contact/StrangerImpl.kt
Labels: ready-to-merge

#1689 Fix AbsoluteFileFolder resolving with absolute path
  mirai-core/src/commonMain/kotlin/contact/file/AbsoluteFolderImpl.kt
  mirai-core/src/commonMain/kotlin/contact/file/AbstractAbsoluteFileFolder.kt
Labels: bug, M

#1673 Add `Image.Factory` and `Image.Builder` for constructing `Image` inst…
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/IMirai.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
  mirai-core/src/commonMain/kotlin/message/InternalImageProtocolImpl.kt
  mirai-core/src/commonMain/kotlin/message/imagesImpl.kt
  mirai-core/src/commonTest/kotlin/message/ImageBuilderTest.kt
Labels: feature, M, ready-to-merge
