Repository mamoe/mirai, pull requests merged in 2021-09, with the labels that each got.

#1465 Snapshots publishing
  .github/workflows/release.yml
  .github/workflows/snapshots.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/JvmPublishing.kt
  ci-release-helper/build.gradle.kts
  docs/ConfiguringProjects.md
  docs/UsingSnapshots.md
  mirai-core-all/build.gradle.kts
  settings.gradle.kts
Labels: M

#1500 Decode packets in netty event loop group
  mirai-core/src/commonMain/kotlin/network/impl/netty/NettyNetworkHandler.kt
  mirai-core/src/commonTest/kotlin/network/framework/AbstractNettyNHTest.kt
Labels: protocol, N, problem, ready-to-merge

#1490 Ensure `SimpleListenerHost.handleException` is called; Cancel registered listeners in `SimpleListenerHost` when it's completed
  mirai-core-api/src/commonMain/kotlin/event/EventChannel.kt
  mirai-core-api/src/jvmTest/kotlin/event/JvmMethodEventsTest.kt
Labels: M, problem, ready-to-merge

#1525 Support group disband kind decoding
  mirai-core-api/src/commonMain/kotlin/event/events/group.kt
  mirai-core/src/commonMain/kotlin/network/notice/group/GroupOrMemberListNoticeProcessor.kt
Labels: feature, protocol, M, ready-to-merge

#1551 Fix `OnlineAudio.urlForDownload` not exists when using pad with private chatting
  mirai-core/src/commonMain/kotlin/network/notice/priv/PrivateMessageProcessor.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/proto/Msg.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/PacketFactory.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/voice/PttStore.kt
Labels: protocol, problem, ready-to-merge

#1549 Fix #1546, revert wrong changes and request system messages
  mirai-core/src/commonMain/kotlin/network/notice/priv/FriendNoticeProcessor.kt
Labels: bug, protocol, N, ready-to-merge

#1548 Add height, width, size and imageType attribute to Image class
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
  mirai-core-utils/src/commonMain/kotlin/Files.kt
  mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt
  mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
  mirai-core/src/commonMain/kotlin/contact/SendMessageHandler.kt
  mirai-core/src/commonMain/kotlin/message/ImageDecoder.kt
  mirai-core/src/commonMain/kotlin/message/imagesImpl.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/proto/Msg.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/image/ImgStore.kt
  mirai-core/src/commonTest/kotlin/message/ImageReadingTest.kt
Labels: feature, protocol, N, ready-to-merge

#1561 修改错别字
  docs/ConciseAPI.md
Labels: documentation

#1520 支持获取消息记录 (漫游消息)
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/contact/Friend.kt
  mirai-core-api/src/commonMain/kotlin/contact/roaming/RoamingMessageFilter.kt
  mirai-core-api/src/commonMain/kotlin/contact/roaming/RoamingMessages.kt
  mirai-core-api/src/commonMain/kotlin/contact/roaming/RoamingSupported.kt
  mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
  mirai-core/src/commonMain/kotlin/contact/roaming/RoamingMessagesImpl.kt
  mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/PacketFactory.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/MessageSvc.PbGetRoamMsgReq.kt
Labels: feature, protocol

#1522 Support for switching anonymousChat settings
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/contact/Group.kt
  mirai-core/src/commonMain/kotlin/contact/GroupSettingsImpl.kt
  mirai-core/src/commonMain/kotlin/contact/info/GroupInfoImpl.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/PacketFactory.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
Labels: feature, protocol, N, ready-to-merge

#1531 Clarify specialTitle docs and support to detect specialTitle changes
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  docs/EventList.md
  mirai-core-api/src/commonMain/kotlin/contact/Member.kt
  mirai-core-api/src/commonMain/kotlin/contact/NormalMember.kt
  mirai-core-api/src/commonMain/kotlin/data/GroupInfo.kt
  mirai-core-api/src/commonMain/kotlin/event/events/group.kt
  mirai-core/src/commonMain/kotlin/network/notice/group/GroupMessageProcessor.kt
  mirai-core/src/commonMain/kotlin/network/notice/group/GroupNotificationProcessor.kt
  mirai-core/src/commonMain/kotlin/utils/string.kt
Labels: feature, protocol, N, ready-to-merge

#1530 Update struct data
  mirai-core/src/commonMain/kotlin/network/protocol/data/jce/TroopList.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/proto/Cmd0x857.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/proto/msgType0x210.kt
Labels: enhancement, N, problem, ready-to-merge

#1568 Refine MessageSource
  mirai-core/src/commonMain/kotlin/message/MessageSourceInternal.kt
  mirai-core/src/commonMain/kotlin/message/RefinableMessage.kt
  mirai-core/src/commonMain/kotlin/message/incomingSourceImpl.kt
Labels: bug, N, ready-to-merge
