Repository mamoe/mirai, pull requests merged in 2021-02, with the labels that each got.

#957 add drinkal/Mirai-js
  docs/README.md
Labels: documentation

#960 Update README.md
  docs/README.md
Labels: documentation

#991 Contact list cache
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/contact/MemberPermission.kt
  mirai-core-api/src/commonMain/kotlin/data/FriendInfo.kt
  mirai-core-api/src/commonMain/kotlin/event/events/bot.kt
  mirai-core-api/src/commonMain/kotlin/event/events/friend.kt
  mirai-core-api/src/commonMain/kotlin/event/events/group.kt
  mirai-core-api/src/commonMain/kotlin/event/events/types.kt
  mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt
  mirai-core-utils/src/commonMain/kotlin/IO.kt
  mirai-core-utils/src/commonMain/kotlin/Serialization.kt
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
  mirai-core/src/commonMain/kotlin/QQAndroidBot.kt
  mirai-core/src/commonMain/kotlin/contact/AbstractMember.kt
  mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt
  mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
  mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
  mirai-core/src/commonMain/kotlin/contact/SendMessageHandler.kt
  mirai-core/src/commonMain/kotlin/contact/StrangerImpl.kt
  mirai-core/src/commonMain/kotlin/contact/info/FriendInfoImpl.kt
  mirai-core/src/commonMain/kotlin/contact/info/GroupInfoImpl.kt
  mirai-core/src/commonMain/kotlin/contact/info/MemberInfoImpl.kt
  mirai-core/src/commonMain/kotlin/contact/info/StrangerInfoImpl.kt
  mirai-core/src/commonMain/kotlin/network/BotNetworkHandler.kt
  mirai-core/src/commonMain/kotlin/network/ContactListCache.kt
  mirai-core/src/commonMain/kotlin/network/ContactUpdater.kt
  mirai-core/src/commonMain/kotlin/network/handler/QQAndroidBotNetworkHandler.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/jce/SvcReqRegister.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/jce/SvcRespRegister.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/OutgoingPacketAndroid.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/MessageSvc.PbGetMsg.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.PbPushGroupMsg.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.PbPushTransMsg.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/list/StrangerList.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/StatSvc.kt
  mirai-core/src/commonMain/kotlin/utils/ScheduledJob.kt
  mirai-core/src/commonTest/kotlin/ScheduledJobTest.kt
Labels: feature, protocol

#1018 Support Dice
  binary-compatibility-validator/api/binary-compatibility-validator.api
  docs/Messages.md
  mirai-core-api/src/commonMain/kotlin/internal/message/MessageSerializersImpl.kt
  mirai-core-api/src/commonMain/kotlin/message/code/internal/impl.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Dice.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MarketFace.kt
  mirai-core-api/src/commonTest/kotlin/message/code/TestMiraiCode.kt
  mirai-core/src/commonMain/kotlin/contact/SendMessageHandler.kt
  mirai-core/src/commonMain/kotlin/message/MarketFaceImpl.kt
  mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
  mirai-core/src/commonMain/kotlin/message/faceImpl.kt
  mirai-core/src/jvmTest/kotlin/message/data/MessageSerializationTest.kt
Labels: N, feature, protocol

#1015 Fix wrong decoding on ConfigPushSvc and update default server list
  mirai-core/src/commonMain/kotlin/network/QQAndroidClient.kt
  mirai-core/src/commonMain/kotlin/network/handler/QQAndroidBotNetworkHandler.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/jce/ConfigPush.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/ConfigPushSvc.kt
Labels: M, protocol, ready-to-merge, 　bug　

#1044 MiraiCode of MusicShare
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/message/code/internal/impl.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MusicShare.kt
  mirai-core-api/src/commonTest/kotlin/message/code/TestMiraiCode.kt
Labels: feature

#1049 Update to Kotlin 1.4.30
  binary-compatibility-validator/api/binary-compatibility-validator.api
  buildSrc/src/main/kotlin/Versions.kt
  gradle/wrapper/gradle-wrapper.properties
  mirai-core-api/src/commonMain/kotlin/contact/NormalMember.kt
  mirai-core-api/src/commonMain/kotlin/event/select.kt
Labels: task

#989 Android target
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/android/build.gradle.kts
  binary-compatibility-validator/api/binary-compatibility-validator.api
  binary-compatibility-validator/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Mpp.kt
  buildSrc/src/main/kotlin/ProjectConfigure.kt
  buildSrc/src/main/kotlin/Versions.kt
  buildSrc/src/main/kotlin/androidutil/AndroidApiLevelCheck.kt
  gradle.properties
  mirai-core-all/build.gradle.kts
  mirai-core-api/build.gradle.kts
  mirai-core-api/src/androidMain/kotlin/findMiraiInstance.android.kt
  mirai-core-api/src/androidMain/kotlin/utils/LoginSolver.android.kt
  mirai-core-api/src/androidMain/kotlin/utils/PlatformLogger.android.kt
  mirai-core-api/src/androidMain/kotlin/utils/SingleFileLogger.android.kt
  mirai-core-api/src/commonMain/kotlin/internal/event/JvmMethodListenersInternal.kt
  mirai-core-api/src/commonMain/kotlin/internal/utils/StdoutLogger.kt
  mirai-core-api/src/commonMain/kotlin/message/code/internal/impl.kt
  mirai-core-api/src/commonMain/kotlin/message/data/CustomMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/impl.kt
  mirai-core-api/src/commonMain/kotlin/utils/FileLogger.kt
  mirai-core-api/src/commonMain/kotlin/utils/LoginSolver.kt
  mirai-core-api/src/commonMain/kotlin/utils/MiraiLogger.kt
  mirai-core-api/src/commonMain/kotlin/utils/SingleFileLogger.kt
  mirai-core-api/src/commonMain/kotlin/utils/SwingSolver.kt
  mirai-core-api/src/jvmMain/kotlin/utils/LoginSolver.jvm.kt
  mirai-core-api/src/jvmMain/kotlin/utils/PlatformLogger.jvm.kt
  mirai-core-api/src/jvmMain/kotlin/utils/SingleFileLogger.jvm.kt
  mirai-core-api/src/jvmMain/kotlin/utils/SwingSolver.kt
  mirai-core-utils/build.gradle.kts
  mirai-core-utils/src/androidMain/kotlin/Actuals.kt
  mirai-core-utils/src/commonMain/kotlin/Bytes.kt
  mirai-core-utils/src/commonMain/kotlin/MiraiPlatformUtils.kt
  mirai-core-utils/src/commonMain/kotlin/StandardUtils.kt
  mirai-core-utils/src/jvmMain/kotlin/Actuals.kt
  mirai-core-utils/src/main/AndroidManifest.xml
  mirai-core/build.gradle.kts
  mirai-core/src/androidMain/kotlin/utils/crypto/ECDHJvmDesktop.kt
  settings.gradle.kts
Labels: N, feature, ready-to-merge, task
