Repository mamoe/mirai, pull requests merged in 2021-08, with the labels that each got.

#1457 支持在踢出群成员时选择是否拉黑
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/contact/NormalMember.kt
  mirai-core/src/commonMain/kotlin/contact/NormalMemberImpl.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
Labels: N, feature, protocol

#1309 Add `RequestEventData` for saving request events
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/data/RequestEventData.kt
Labels: feature, N

#1481 Bypass BC deprecation check on Android
  buildSrc/src/main/kotlin/Versions.kt
  mirai-core/build.gradle.kts
  mirai-core/src/androidMain/kotlin/utils/crypto/ECDHJvmDesktop.kt
Labels: problem, ready-to-merge
