Repository mamoe/mirai, pull requests merged in 2021-06, with the labels that each got.

#1285 Redesign LoginSolver
  mirai-core-api/src/jvmMain/kotlin/utils/LoginSolver.TxCaptchaHelper.kt
  mirai-core-api/src/jvmMain/kotlin/utils/LoginSolver.jvm.kt
  mirai-core-api/src/jvmMain/kotlin/utils/SwingSolver.kt
Labels: N, enhancement, ready-to-merge

#1290 Deprecate `RemoteFile.upload` and relevant extensions, fix #1255
  mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
  mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
Labels: enhancement, problem

#1291 Review docs and improve readability
  docs/Bots.md
  docs/Contacts.md
  docs/EventList.md
  docs/Events.md
  docs/Messages.md
  mirai-core-api/README.md
Labels: M, documentation

#1248 Clearify docs for `ExternalResource` and `RemoteFile`
  mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
  mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
Labels: documentation

#1314 fix: do trimming properly in `startsWith` & `endsWith`, #1282
  mirai-core-api/src/commonMain/kotlin/event/MessageSubscribersBuilder.kt
  mirai-core-api/src/commonMain/kotlin/internal/event/messageSubscribersInternal.kt
Labels: N, problem

#1326 Create `Concise API`
  docs/ConciseAPI.md
  docs/CoreAPI.md
Labels: M, documentation

#1335 Fix #1334, update pb and fix private image upload issue
  mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt
  mirai-core/src/commonMain/kotlin/network/highway/Highway.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/proto/Cmd0x352.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/proto/Highway.kt
Labels: problem, protocol, ready-to-merge

#1355 Add version info in `META-INF/MANIFEST.MF`
  build.gradle.kts
  buildSrc/src/main/kotlin/ProjectConfigure.kt
Labels: N, enhancement, ready-to-merge

#1275 Remove redundant spaces in rendering ForwardMessage
  mirai-core-api/src/commonMain/kotlin/message/data/ForwardMessage.kt
Labels: N, enhancement, ready-to-merge

#1257 Fix #1192, request admin when loading groups
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
  mirai-core/src/commonMain/kotlin/contact/info/MemberInfoImpl.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/proto/OIDB.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/PacketFactory.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
Labels: problem, protocol, ready-to-merge

#1237 ECDH: Replacing old curve, thanks to MiraiGo
  mirai-core/src/androidMain/kotlin/utils/crypto/ECDHJvmDesktop.kt
  mirai-core/src/commonMain/kotlin/QQAndroidBot.kt
  mirai-core/src/commonMain/kotlin/network/QQAndroidClient.kt
  mirai-core/src/commonMain/kotlin/network/components/EcdhInitialPublicKeyUpdater.kt
  mirai-core/src/commonMain/kotlin/network/components/PacketCodec.kt
  mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
  mirai-core/src/commonMain/kotlin/network/context/AccountSecrets.kt
  mirai-core/src/commonMain/kotlin/network/context/SsoSession.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/EncryptMethod.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/OutgoingPacketAndroid.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin10.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin2.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin20.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
  mirai-core/src/commonMain/kotlin/utils/crypto/ECDH.kt
  mirai-core/src/commonTest/kotlin/network/framework/sessionUtils.kt
  mirai-core/src/jvmMain/kotlin/utils/crypto/ECDHJvmDesktop.kt
Labels: M, enhancement, ready-to-merge

#1260 Update system face
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
Labels: N, feature, ready-to-merge

#1141 GroupAnnoucement
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/LowLevelApiAccessor.kt
  mirai-core-api/src/commonMain/kotlin/contact/Group.kt
  mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
  mirai-core-api/src/commonMain/kotlin/data/GroupAnnouncement.kt
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
  mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
Labels: M, feature

#1241 StatSvc.SimpleGet: Decode the resp
  mirai-core/src/commonMain/kotlin/network/handler/NetworkHandlerSupport.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/proto/StatSvcSimpleGet.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/StatSvc.kt
  mirai-core/src/commonTest/kotlin/network/impl/netty/NettyBotLifecycleTest.kt
Labels: M, enhancement, protocol

#1310 Private voice support
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/contact/Friend.kt
  mirai-core-api/src/commonMain/kotlin/contact/Group.kt
  mirai-core-api/src/commonMain/kotlin/contact/VoiceSupported.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Voice.kt
  mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
  mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
  mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
  mirai-core/src/commonMain/kotlin/network/protocol/data/proto/Cmd0x346.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/MessageSvc.PbGetMsg.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/MessageSvc.PbSendMsg.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/voice/PttStore.kt
Labels: N, feature, protocol, ready-to-merge

#1372 Fix #1322, remove redundant cookie
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
Labels: N, bug, protocol
