Repository mamoe/mirai, pull requests merged in 2021-12, with the labels that each got.

#1708 Dokka
  .github/workflows/build.yml
  .github/workflows/doc.yml
  build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  mirai-core-api/src/commonMain/kotlin/contact/Group.kt
  mirai-dokka/.gitignore
  mirai-dokka/build.gradle.kts
  mirai-dokka/frontend/ext.js
  mirai-dokka/src/BuildVersionList.kt
  mirai-dokka/src/DeployToGitHub.kt
  mirai-dokka/src/Prepare.kt
  mirai-dokka/src/system.kt
  settings.gradle.kts
Labels: enhancement, N, documentation, task, ready-to-merge

#1712 Support `AbsoluteFolder.resolveFolderById`
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/contact/file/AbsoluteFolder.kt
  mirai-core/src/commonMain/kotlin/contact/file/AbsoluteFolderImpl.kt
  mirai-core/src/commonTest/kotlin/contact/file/AbsoluteFolderTest.kt
Labels: feature, N, ready-to-merge

#1716 Revert prohibition of sending file message:
  mirai-core-utils/src/commonMain/kotlin/ExceptionCollector.kt
  mirai-core/src/commonMain/kotlin/contact/util.kt
Labels: M, task

#1724 upgrade log4j version to prevent vulnerability
  buildSrc/src/main/kotlin/Versions.kt
Labels: enhancement, M, problem

#1741 [CONSOLE] Integration Test
  mirai-console/backend/integration-test/README.md
  mirai-console/backend/integration-test/build.gradle.kts
  mirai-console/backend/integration-test/src/AbstractTestPoint.kt
  mirai-console/backend/integration-test/src/AbstractTestPointAsPlugin.kt
  mirai-console/backend/integration-test/src/IntegrationTestBootstrap.kt
  mirai-console/backend/integration-test/src/MiraiConsoleIntegrationTestLauncher.kt
  mirai-console/backend/integration-test/src/utils.kt
  mirai-console/backend/integration-test/test/MiraiConsoleIntegrationTestBootstrap.kt
  mirai-console/backend/integration-test/test/testpoints/DoNothingPoint.kt
  mirai-console/backend/integration-test/test/testpoints/MCITBSelfAssertions.kt
  mirai-console/backend/integration-test/testers/.gitignore
  mirai-console/backend/integration-test/testers/MCITSelfTestPlugin/resources/META-INF/services/net.mamoe.mirai.console.plugin.jvm.JvmPlugin
  mirai-console/backend/integration-test/testers/MCITSelfTestPlugin/src/MCITSelfTestPlugin.kt
  mirai-console/backend/integration-test/testers/README.md
  mirai-console/backend/integration-test/testers/tester.template.gradle.kts
  settings.gradle.kts
Labels: enhancement, console

#1751 修复设置 redirectNetworkLogToDirectory 后日志 identity 为 Bot 的问题
  mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt
Labels: bug, M

#1753 Deprecate experimental `EventChannel.asChannel` and add `EventChannel.forwardToChannel`
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/event/EventChannel.kt
  mirai-core-api/src/jvmTest/kotlin/event/EventChannelTest.kt
Labels: feature, N, ready-to-merge
