Repository mamoe/mirai, pull requests merged in 2021-05, with the labels that each got.

#1230 Rework seq system
  mirai-core-utils/src/commonMain/kotlin/RandomUtils.kt
  mirai-core/src/commonMain/kotlin/network/QQAndroidClient.kt
  mirai-core/src/commonMain/kotlin/network/highway/Highway.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/MessageSvc.PbSendMsg.kt
Labels: ready-to-merge

#1232 Correct the seq logic, fix #1094
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/MessageSvc.PbGetMsg.kt
Labels: bug, protocol, ready-to-merge

#1234 Add inline `BotFactory.newBot` for Kotlin DSL. fix #1233
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/BotFactory.kt
  mirai-core/src/jvmTest/kotlin/BotFactoryTest.kt
Labels: ready-to-merge

#1242 OnlinePush.SidTicketExpired: Refresh token and register online
  mirai-core/src/commonMain/kotlin/network/protocol/packet/PacketFactory.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.SidExpired.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin10.kt
Labels: enhancement, protocol

#1231 Introduce MemberNick class and correct nameCard decoding, Fix #1151
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.PbPushGroupMsg.kt
Labels: N, problem
