Repository mamoe/mirai, pull requests merged in 2021-10, with the labels that each got.

#1523 Add mac and ipad protocol from miraiGo
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt
  mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt
Labels: feature, protocol, N

#1633 修复群联系人保存
  mirai-core/src/commonMain/kotlin/network/components/ContactUpdater.kt
Labels: bug, M, ready-to-merge

#1589 Redesign group files
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/contact/FileSupported.kt
  mirai-core-api/src/commonMain/kotlin/contact/file/AbsoluteFile.kt
  mirai-core-api/src/commonMain/kotlin/contact/file/AbsoluteFileFolder.kt
  mirai-core-api/src/commonMain/kotlin/contact/file/AbsoluteFolder.kt
  mirai-core-api/src/commonMain/kotlin/contact/file/RemoteFiles.kt
  mirai-core-api/src/commonMain/kotlin/message/data/FileMessage.kt
  mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
  mirai-core-api/src/commonMain/kotlin/utils/ProgressionCallback.kt
  mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
  mirai-core-utils/src/commonMain/kotlin/ResultExtensions.kt
  mirai-core/src/commonMain/kotlin/contact/ContactAware.kt
  mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
  mirai-core/src/commonMain/kotlin/contact/file/AbsoluteFileImpl.kt
  mirai-core/src/commonMain/kotlin/contact/file/AbsoluteFolderImpl.kt
  mirai-core/src/commonMain/kotlin/contact/file/AbstractAbsoluteFileFolder.kt
  mirai-core/src/commonMain/kotlin/contact/file/FileProtocol.kt
  mirai-core/src/commonMain/kotlin/contact/file/RemoteFilesImpl.kt
  mirai-core/src/commonMain/kotlin/message/FileMessageImpl.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/GroupFile.kt
  mirai-core/src/commonMain/kotlin/utils/RemoteFileImpl.kt
Labels: enhancement

#1634 删除多余登录服务器
  mirai-core/src/commonMain/kotlin/network/QQAndroidClient.kt
  mirai-core/src/commonMain/kotlin/network/components/ServerList.kt
Labels: enhancement, protocol, ready-to-merge
