Repository mamoe/mirai, pull requests merged in 2021-07, with the labels that each got.

#1368 Voice serialization
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/LowLevelApiAccessor.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Voice.kt
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
  mirai-core/src/jvmTest/kotlin/message/data/MessageSerializationTest.kt
Labels: N, enhancement, ready-to-merge

#1240 StatSvc.Register: Provide SSO Ip and correct logic
  mirai-core/src/commonMain/kotlin/QQAndroidBot.kt
  mirai-core/src/commonMain/kotlin/network/components/ServerList.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/StatSvc.kt
  mirai-core/src/commonMain/kotlin/utils/type.kt
  mirai-core/src/commonTest/kotlin/network/ServerListTest.kt
  mirai-core/src/commonTest/kotlin/network/framework/AbstractNettyNHTestWithSelector.kt
  mirai-core/src/commonTest/kotlin/network/framework/AbstractRealNetworkHandlerTest.kt
  mirai-core/src/commonTest/kotlin/network/impl/netty/NettyAddressChangedTest.kt
  mirai-core/src/commonTest/kotlin/network/impl/netty/NettyBotNormalLoginTest.kt
Labels: M, bug, protocol, ready-to-merge

#1383 ExternalResourceLeakObserver
  mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalImageImpls.kt
  mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalResourceLeakObserver.kt
Labels: N, enhancement, ready-to-merge

#1385 Add `@NotStableForInheritance` and apply it to suitable classes
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/Bot.kt
  mirai-core-api/src/commonMain/kotlin/IMirai.kt
  mirai-core-api/src/commonMain/kotlin/LowLevelApiAccessor.kt
  mirai-core-api/src/commonMain/kotlin/contact/AnonymousMember.kt
  mirai-core-api/src/commonMain/kotlin/contact/Contact.kt
  mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
  mirai-core-api/src/commonMain/kotlin/contact/FileSupported.kt
  mirai-core-api/src/commonMain/kotlin/contact/Friend.kt
  mirai-core-api/src/commonMain/kotlin/contact/Group.kt
  mirai-core-api/src/commonMain/kotlin/contact/Member.kt
  mirai-core-api/src/commonMain/kotlin/contact/NormalMember.kt
  mirai-core-api/src/commonMain/kotlin/contact/OtherClient.kt
  mirai-core-api/src/commonMain/kotlin/contact/Stranger.kt
  mirai-core-api/src/commonMain/kotlin/contact/TempUser.kt
  mirai-core-api/src/commonMain/kotlin/contact/User.kt
  mirai-core-api/src/commonMain/kotlin/contact/UserOrBot.kt
  mirai-core-api/src/commonMain/kotlin/contact/VoiceSupported.kt
  mirai-core-api/src/commonMain/kotlin/event/Listener.kt
  mirai-core-api/src/commonMain/kotlin/message/MessageReceipt.kt
  mirai-core-api/src/commonMain/kotlin/message/MessageSerializers.kt
  mirai-core-api/src/commonMain/kotlin/message/code/CodableMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/FileMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/HummerMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MarketFace.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MessageChain.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MessageSource.kt
  mirai-core-api/src/commonMain/kotlin/message/data/RichMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/UnsupportedMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Voice.kt
  mirai-core-api/src/commonMain/kotlin/utils/Annotations.kt
  mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
Labels: N, enhancement

#1393 修改了一些文档中的错误
  docs/Bots.md
Labels: documentation

#1387 Add third-party Python SDK YiriMirai
  docs/README.md
Labels: documentation

#1382 `Face.toString`: use `contentToString()` for better readability
  mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
Labels: N, enhancement, ready-to-merge

#1408 Fix #1405, before it is a compiler undefined behavior
  mirai-core/src/commonMain/kotlin/network/components/PacketCodec.kt
Labels: M, bug, protocol, ready-to-merge
