Repository mamoe/mirai, pull requests merged in 2021-04, with the labels that each got.

#1148 Fix `ForwardMessage` display
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/MultiMsg.kt
Labels: N, protocol

#1150 Login: Update tlv and solve constant connection dropping issue
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt
  mirai-core/src/commonMain/kotlin/network/handler/QQAndroidBotNetworkHandler.kt
  mirai-core/src/commonMain/kotlin/network/keys.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/PacketFactory.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/StatSvc.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLoginExt.kt
Labels: M, enhancement, protocol

#1147 Postpone error reporting in parsing in `NewContact`
  mirai-core/src/commonMain/kotlin/network/Packet.kt
  mirai-core/src/commonMain/kotlin/network/handler/QQAndroidBotNetworkHandler.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/NewContact.kt
Labels: N, enhancement

#1154 Fast login
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt
  mirai-core/src/commonMain/kotlin/network/handler/QQAndroidBotNetworkHandler.kt
  mirai-core/src/commonMain/kotlin/network/keys.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/PacketFactory.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/Tlv.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/ConfigPushSvc.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/StatSvc.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin10.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLoginExt.kt
Labels: protocol, 　bug　

#1142 Update docs for messages
  docs/Messages.md
  mirai-core-api/src/commonMain/kotlin/IMirai.kt
  mirai-core-api/src/commonMain/kotlin/contact/NormalMember.kt
  mirai-core-api/src/commonMain/kotlin/event/events/MessageEvent.kt
  mirai-core-api/src/commonMain/kotlin/message/code/MiraiCode.kt
  mirai-core-api/src/commonMain/kotlin/message/data/At.kt
  mirai-core-api/src/commonMain/kotlin/message/data/AtAll.kt
  mirai-core-api/src/commonMain/kotlin/message/data/ConstrainSingle.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Dice.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
  mirai-core-api/src/commonMain/kotlin/message/data/FlashImage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/ForwardMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MarketFace.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Message.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MessageChain.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MessageChainBuilder.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MessageKey.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MessageSource.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MessageSourceBuilder.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MusicShare.kt
  mirai-core-api/src/commonMain/kotlin/message/data/PlainText.kt
  mirai-core-api/src/commonMain/kotlin/message/data/PokeMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/QuoteReply.kt
  mirai-core-api/src/commonMain/kotlin/message/data/RichMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/ShowImageFlag.kt
  mirai-core-api/src/commonMain/kotlin/message/data/SingleMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/VipFace.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Voice.kt
  mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
  mirai-core/src/commonMain/kotlin/message/LongMessageInternal.kt
  mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
Labels: documentation

#1116 Rename `RichMessageOrigin` to `MessageOrigin`
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/internal/message/MessageSerializersImpl.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Deprecated.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MessageOrigin.kt
  mirai-core-api/src/commonMain/kotlin/message/data/SingleMessage.kt
  mirai-core/src/commonMain/kotlin/message/LongMessageInternal.kt
  mirai-core/src/commonMain/kotlin/message/MarketFaceImpl.kt
  mirai-core/src/commonMain/kotlin/message/lightApp.kt
  mirai-core/src/jvmTest/kotlin/message/data/MessageSerializationTest.kt
Labels: enhancement

#1161 buildscript: fix task not found errors when android sdk not available
  buildSrc/src/main/kotlin/analyzes/CompiledCodeVerify.kt
  mirai-core-api/build.gradle.kts
  mirai-core-utils/build.gradle.kts
  mirai-core/build.gradle.kts
Labels: enhancement, ready-to-merge

#1162 Add `ForwardMessageBuilder.toRawForwardMessage` and make `RawForwardMessage` stable
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/message/data/ForwardMessage.kt
Labels: feature, ready-to-merge

#1159 Fix kt compiler errors
  .github/workflows/build.yml
  .github/workflows/doc.yml
  .github/workflows/release.yml
  binary-compatibility-validator/kt-compile-edit/mirai-core-api-compileKotlinAndroid.txt
  binary-compatibility-validator/kt-compile-edit/mirai-core-api-compileKotlinJvm.txt
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  buildSrc/src/main/kotlin/analyzes/AsmUtil.kt
  buildSrc/src/main/kotlin/analyzes/NoSuchMethodAnalyzer.kt
  buildSrc/src/main/kotlin/postktcompile/PostKotlinCompile.kt
  mirai-core/src/commonMain/kotlin/utils/RemoteFileImpl.kt
Labels: enhancement, ready-to-merge

#1169 Fix key refresh failed when refresh again and update dumped data
  mirai-core/src/commonMain/kotlin/network/QQAndroidClient.kt
  mirai-core/src/commonMain/kotlin/network/keys.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin10.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin15.kt
  mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt
Labels: protocol, 　bug　

#1170 fix #1155
  mirai-core/src/commonMain/kotlin/contact/NormalMemberImpl.kt
Labels: 　bug　

#1174 Fix https://github.com/mamoe/mirai/pull/1167#discussion_r608537316
  buildSrc/src/main/kotlin/postktcompile/PostKotlinCompile.kt
Labels: N, problem

#1180 Deprecate `RemoteFile.moveTo(String)` for ambiguous behavior
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
  mirai-core/src/commonMain/kotlin/utils/RemoteFileImpl.kt
Labels: problem

#1178 添加管理员修改功能
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/contact/NormalMember.kt
  mirai-core/src/commonMain/kotlin/contact/NormalMemberImpl.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/PacketFactory.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
Labels: feature, protocol, ready-to-merge

#1195 Add RefineContext for refining
  mirai-core/src/commonMain/kotlin/message/LongMessageInternal.kt
  mirai-core/src/commonMain/kotlin/message/MarketFaceImpl.kt
  mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
  mirai-core/src/commonMain/kotlin/message/RefinableMessage.kt
  mirai-core/src/commonMain/kotlin/message/lightApp.kt
  mirai-core/src/jvmTest/kotlin/message/data/MessageRefineTest.kt
Labels: N, enhancement

#1196 Support receive nested ForwardMessages
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
  mirai-core/src/commonMain/kotlin/QQAndroidBot.kt
  mirai-core/src/commonMain/kotlin/message/LongMessageInternal.kt
  mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
  mirai-core/src/jvmTest/kotlin/message/data/MessageRefineTest.kt
Labels: feature, protocol, ready-to-merge

#1197 fix: serialization plugin should not be put into runtime classpath
  mirai-core-api/build.gradle.kts
  mirai-core-utils/build.gradle.kts
Labels: enhancement

#1202 补充mirai-hello-world
  docs/ConfiguringProjects.md
Labels: documentation

#1214 Fix duplicate register packet
  mirai-core/src/commonMain/kotlin/network/handler/QQAndroidBotNetworkHandler.kt
Labels: 　bug　

#1227 修复添加依赖库错误
  docs/ConfiguringProjects.md
Labels: documentation

#1228 feat: support kugou,kuwo music share
  binary-compatibility-validator/android/api/binary-compatibility-validator-android.api
  binary-compatibility-validator/api/binary-compatibility-validator.api
  mirai-core-api/src/commonMain/kotlin/message/data/MusicShare.kt
Labels: feature, ready-to-merge
