Repository mamoe/mirai, pull requests merged in 2022-01, with the labels that each got.

#1718 Secrets Protection
  mirai-console/backend/mirai-console/src/internal/data/builtins/AutoLoginConfig.kt
  mirai-core-utils/src/commonMain/kotlin/IO.kt
  mirai-core-utils/src/commonMain/kotlin/JvmNioBuffer.kt
  mirai-core-utils/src/commonMain/kotlin/SecretsProtection.kt
  mirai-core-utils/src/jvmTest/kotlin/SecretsProtectionTest.kt
  mirai-core/src/commonMain/kotlin/BotAccount.kt
Labels: enhancement, N, ready-to-merge

#1711 允许使用 IPAD 协议发送戳一戳
  mirai-core-api/src/commonMain/kotlin/message/action/Nudge.kt
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
Labels: N, t:problem, z:ready-to-merge

#1748 add: TemporalArgumentParser
  mirai-console/backend/mirai-console/src/command/descriptor/CommandArgumentContext.kt
  mirai-console/backend/mirai-console/src/command/descriptor/CommandArgumentParserBuiltins.kt
  mirai-console/backend/mirai-console/test/command/InstanceTestCommand.kt
Labels: t:feature, N, z:ready-to-merge, s:console

#1774 Review deprecation for 2.10. close #1742
  logging/mirai-logging-log4j2/test/MiraiLog4JAdapterTest.kt
  mirai-console/backend/codegen/src/MessageScopeCodegen.kt
  mirai-console/backend/mirai-console/compatibility-validation/jvm/api/jvm.api
  mirai-console/backend/mirai-console/src/command/CommandSender.kt
  mirai-console/backend/mirai-console/src/data/PluginDataExtensions.kt
  mirai-console/backend/mirai-console/src/internal/util/CommonUtils.kt
  mirai-console/backend/mirai-console/src/permission/PermitteeId.kt
  mirai-console/backend/mirai-console/src/plugin/Plugin.kt
  mirai-console/backend/mirai-console/src/util/MessageScope.kt
  mirai-console/frontend/mirai-console-terminal/build.gradle.kts
  mirai-console/frontend/mirai-console-terminal/src/net/mamoe/mirai/console/pure/MiraiConsolePureLoader.kt
  mirai-console/tools/gradle-plugin/src/main/kotlin/MiraiConsoleExtension.kt
  mirai-core-api/compatibility-validation/android/api/android.api
  mirai-core-api/compatibility-validation/jvm/api/jvm.api
  mirai-core-api/src/androidMain/kotlin/utils/LoginSolver.android.kt
  mirai-core-api/src/commonMain/kotlin/contact/AnonymousMember.kt
  mirai-core-api/src/commonMain/kotlin/contact/Exceptions.kt
  mirai-core-api/src/commonMain/kotlin/contact/FileSupported.kt
  mirai-core-api/src/commonMain/kotlin/contact/Group.kt
  mirai-core-api/src/commonMain/kotlin/contact/NormalMember.kt
  mirai-core-api/src/commonMain/kotlin/data/GroupHonorListData.kt
  mirai-core-api/src/commonMain/kotlin/event/MessageSubscribersBuilder.kt
  mirai-core-api/src/commonMain/kotlin/event/events/MessageEvent.kt
  mirai-core-api/src/commonMain/kotlin/event/events/MessagePostSendEvent.kt
  mirai-core-api/src/commonMain/kotlin/event/events/MessagePreSendEvent.kt
  mirai-core-api/src/commonMain/kotlin/event/subscribeMessages.kt
  mirai-core-api/src/commonMain/kotlin/internal/message/MessageSerializersImpl.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Deprecated.kt
  mirai-core-api/src/commonMain/kotlin/message/data/FileMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
  mirai-core-api/src/commonMain/kotlin/message/data/MessageChain.kt
  mirai-core-api/src/commonMain/kotlin/message/data/SingleMessage.kt
  mirai-core-api/src/commonMain/kotlin/message/data/Voice.kt
  mirai-core-api/src/commonMain/kotlin/network/ForceOfflineException.kt
  mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt
  mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
  mirai-core-api/src/commonMain/kotlin/utils/MiraiLogger.kt
  mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
  mirai-core-api/src/commonTest/kotlin/logging/LoggingCompatibilityTest.kt
  mirai-core-api/src/commonTest/kotlin/utils/TimeTest.kt
  mirai-core-utils/src/commonMain/kotlin/Annotations.kt
  mirai-core-utils/src/commonMain/kotlin/TimeUtils.kt
  mirai-core/src/commonMain/kotlin/BotFactory.kt
  mirai-core/src/commonMain/kotlin/MiraiImpl.kt
  mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/PacketFactory.kt
  mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/MessageSvc.PbSendMsg.kt
  mirai-core/src/commonMain/kotlin/utils/RemoteFileImpl.kt
  mirai-core/src/commonTest/kotlin/test/initPlatform.common.kt
Labels: t:task

#1754 弃用无 receiver 的事件扩展函数, 增加其 `EventChannel` receiver 版本替换
  mirai-core-api/compatibility-validation/android/api/android.api
  mirai-core-api/compatibility-validation/jvm/api/jvm.api
  mirai-core-api/src/commonMain/kotlin/event/EventChannel.kt
  mirai-core-api/src/commonMain/kotlin/event/Extensions.kt
  mirai-core-api/src/commonMain/kotlin/event/deprecated.nextEvent.kt
  mirai-core-api/src/commonMain/kotlin/event/deprecated.nextEventAsync.kt
  mirai-core-api/src/commonMain/kotlin/event/deprecated.syncFromEvent.kt
  mirai-core-api/src/commonMain/kotlin/message/utils.kt
  mirai-core-api/src/jvmTest/kotlin/event/NextEventTest.kt
Labels: t:feature, N, x:breaking-change
