Repository mamoe/mirai, pull requests merged in 2023-04, with the labels that each got.

#2610 review: group active protocol
  mirai-core/src/commonMain/kotlin/contact/active/GroupActiveProtocol.kt
Labels: s:core

#2622 [idea] feat: generate gradle-wrapper.properties and src/test directory
  mirai-console/tools/intellij-plugin/resources/fileTemplates/code/Gradle gradle-wrapper.properties.ft
  mirai-console/tools/intellij-plugin/resources/fileTemplates/code/Gradle gradle-wrapper.properties.html
  mirai-console/tools/intellij-plugin/src/assets/Assets.kt
  mirai-console/tools/intellij-plugin/src/assets/FileTemplateRegistrar.kt
  mirai-console/tools/intellij-plugin/src/wizard/MiraiModuleBuilder.kt
  mirai-console/tools/intellij-plugin/src/wizard/ProjectAssetsProvider.kt
Labels: z:ready-to-merge

#2631 [idea] feat: set jvmTarget version explicitly
  mirai-console/tools/intellij-plugin/resources/fileTemplates/code/Plugin build.gradle.ft
  mirai-console/tools/intellij-plugin/resources/fileTemplates/code/Plugin build.gradle.kts.ft
Labels: z:ready-to-merge, s:idea
